cask_args appdir: '/Applications'
tap "homebrew/cask"
tap "homebrew/cask-drivers"

brew 'autoconf'
brew 'automake'
brew 'coreutils'
brew 'doxygen'
brew 'openssl'
brew 'jpeg'
brew 'libpng'
brew 'libtiff'
brew 'libgda'
brew 'wxmac'
brew 'gdbm'
brew 'git'
brew 'grc'
brew 'libevent'
brew 'libxml2'
brew 'pcre'
brew 'pkg-config'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'wget'
brew 'zsh'
brew 'starship'
brew 'mas'
brew 'neovim'
brew 'fzf'
brew 'ripgrep'
brew 'universal-ctags/universal-ctags/universal-ctags', args: ['HEAD']
brew 'git-delta'
brew 'asdf'

cask 'appcleaner'
cask 'osxfuse'
cask 'rectangle'
cask 'spotify'
cask 'telegram'
cask 'the-unarchiver'
cask 'visual-studio-code'
cask 'alfred'
cask 'logitech-options'

mas 'pixelmator', id: 407963104
mas 'amphetamine', id: 937984704
mas 'Xcode', id: 497799835
mas 'Slack', id: 803453959
mas 'NordVPN IKE - Unlimited VPN', id: 1116599239
