#!/usr/bin/env bash

set -e

install_vundle() {
  if [ ! -d $HOME/.vim/bundle/vundle ]; then
    git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
    vim +BundleInstall +qall
    sh "`pwd`/vim/install.sh"
  fi
}

install_vundle
