#!/usr/bin/env bash

DOTFILES_ROOT="`pwd`"

set -e

run_installers () {
  installers=(
    'vim/install.sh'
  )

  for installer in $installers
  do
    sh -c "${DOTFILES_ROOT}/${installer}"
  done
}

run_installers
