#!/usr/bin/env bash

DOTFILES_ROOT="`pwd`"

set -e

link_files () {
  ln -s $1 $2
}

install_vundle() {
  if [ ! -d $HOME/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/Vundle.vim
    vim +BundleInstall +qall
  fi
}

copy_dotfiles () {
  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"


    if [ -f $dest ] || [ -d $dest ]
    then
      rm -rf $dest
    fi

    link_files $source $dest
  done
}

run_installers () {
  installers=(
    'vim/install.sh'
  )

  for installer in $installers
  do
    sh $DOTFILES_ROOT/$installer
  done
}

copy_dotfiles
install_vundle
run_installers
