#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e
DOTFILES_ROOT="`pwd`"

echo "Linking files..."
sh -c "$DOTFILES_ROOT/script/link"
echo "Done linking files..."

sh -c "$DOTFILES_ROOT/script/bootstrap"
echo "Done bootstraping dotfiles..."

sh -c "$DOTFILES_ROOT/script/install_fonts"
echo "Done installing powerline patched fonts..."

cd "$(dirname $)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
