#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e
DOTFILES_ROOT="`pwd`"

sh -c "$DOTFILES_ROOT/script/bootstrap"
echo "Done bootstraping dotfiles..."

cd "$(dirname $)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
