#!/usr/bin/env bash

DOTFILES_ROOT="`pwd`"

set -e

link_files () {
  ln -sf "$DOTFILES_ROOT/$1" "$HOME/$2"
}

link_files "zsh/zshenv" ".zshenv"
link_files "zsh/zshrc" ".config/zsh/.zshrc"

link_files "alacritty/alacritty.yml" ".config/alacritty/alacritty.yml"
link_files "git/gitignore" ".gitignore"
link_files "git/gitconfig" ".gitconfig"

link_files "ruby/gemrc" ".gemrc"
link_files "ruby/irbrc" ".irbrc"
link_files "starship/starship.toml" ".config/starship.toml"
link_files "rtx/config.toml" ".config/rtx/config.toml"
link_files "tmux/tmux.conf" ".tmux.conf"

link_files "neovim/init.lua" ".config/nvim/init.lua"
link_files "neovim/lua/base.lua" ".config/nvim/lua/base.lua"
link_files "neovim/lua/plugins.lua" ".config/nvim/lua/plugins.lua"
link_files "neovim/lua/aesthetic.lua" ".config/nvim/lua/aesthetic.lua"
link_files "neovim/lua/mappings.lua" ".config/nvim/lua/mappings.lua"
link_files "neovim/lua/autocmd.lua" ".config/nvim/lua/autocmd.lua"
exit 0
