#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e
DOTFILES_ROOT="`pwd`"

echo "Creating required folders..."
[ -d ~/tmp ] || mkdir ~/tmp
[ -d ~/src ] || mkdir ~/src
if [[ ! -a ~/.config ]]
then
  mkdir ~/.config
  mkdir ~/.config/local
  mkdir ~/.config/local/share
  mkdir ~/.config/cache
  mkdir ~/.config/zsh
  mkdir ~/.config/alacritty
  mkdir ~/.config/nvim
fi
echo "Done creating required folders!"

echo "Linking files..."
sh -c "$DOTFILES_ROOT/script/link"
echo "Done linking files!"

cd "$(dirname $)"/..
