#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e
DOTFILES_ROOT="`pwd`"

echo "  🔨 Creating required folders..."
[ -d ~/tmp ] || mkdir ~/tmp
[ -d ~/src ] || mkdir ~/src
[ -d ~/.config ] || mkdir ~/.config
[ -d ~/.config/local ] || mkdir ~/.config/local
[ -d ~/.config/local/share ] || mkdir ~/.config/local/share
[ -d ~/.config/cache ] || mkdir ~/.config/cache
[ -d ~/.config/zsh ] || mkdir ~/.config/zsh
[ -d ~/.config/alacritty ] || mkdir ~/.config/alacritty
[ -d ~/.config/nvim ] || mkdir ~/.config/nvim
echo "  ✅ Done creating required folders!"

echo "  🔗 Linking files..."
sh -c "$DOTFILES_ROOT/script/link"
echo "  ✅ Done with links"

echo "  🤞 Starting with the installers..."

# Install all dependencies
for file in installers/*; do
  sh -c $file
done

echo "  🚀 We're all done and you're ready to rock! 🤘🏻"
