export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

# shortcut to this dotfiles path is $ZSH
export ZSH=$HOME/.dotfiles

export EDITOR="nvim"
export VISUAL="nvim"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# Elixir
export ERL_AFLAGS="-kernel shell_history enabled"

# FZF
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!{.git,node_modules,log,sorbet,rbi,vendor,vcr_cassettes}/*'"
export FZF_DEFAULT_OPTS="--inline-info --height 40% --layout=reverse --border"

# Rust/Cargo
export CARGO_PATH=$HOME/.cargo

# CloudDrive
export CLOUD_DRIVE="$HOME/Library/Mobile Documents/com~apple~CloudDocs"

# Prepend programming language binaries via ASDF shims
PATH="$GOPATH/bin:$PATH"
PATH="$CARGO_PATH/bin:$PATH"
PATH="$ZSH/bin:$PATH"
PATH="$HOME/bin:$PATH"
PATH="$PATH:/usr/local/opt/fzf/bin"
export -U PATH

export LC_ALL=en_US.UTF-8

export LSCOLORS="exfxcxdxbxegedabagacad"
export CLICOLOR=true
export TERM=xterm-256color
. "$HOME/.cargo/env"
