# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# Source all zsh configs
source $ZSH/zsh/config.zsh

# Source all aliases
source $ZSH/zsh/aliases.zsh

# initialize autocomplete here, otherwise functions won't be loaded
autoload -Uz compinit; compinit
autoload -Uz bashcompinit; bashcompinit

source $ZSH/zsh/completion.zsh

# brew
eval "$(/opt/homebrew/bin/brew shellenv)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# asdf
. $(brew --prefix asdf)/libexec/asdf.sh

# Rust/Cargo
. "$HOME/.cargo/env"

# starship.rs
eval "$(starship init zsh)"

